### ISSUE TITLE
Power saving focused configuration

### ISSUE THREAD

**Issue by bamsbamx** [Magisk-Modules-Alt-Repo/ktweak#15]
As far as I know, this script performs various configuration on the kernel to focus on performance by setting multiple parameters of the scheduler. And it actually looks promising

I suggest creating a power-saving-only variant of this script. I think that many many people would be interested on this.

**Comment by tytydraco** [comment]
Hi!

I actually looked into this previously and unfortunately the power gained from reducing the amount of unnecessary scheduler cycles is marginal at best. Rather than a balance between power and performance, it's a balance between latency and throughput.

I'll close this thread for now but feel free to comment here if you have questions or comments! 👍
